#!/bin/bash

echo
echo "to exit, press Ctrl-C and wait for the locomotive to pass"
echo
sleep 3

clear
trap "exit" INT
declare -a ca=( "-a" "-l" "-F" "-c" "-al" "-aF" "-ac" "-lF" "-lc" "-alF" "-alc" "-lFc" "-alFc")
for i in $(seq 1 8192); do
   sl "${ca[$(shuf -i 1-${#ca[@]} -n 1)-1]}"
done

exit 0
